Algoritmo "ex02_boasvindas"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2022
Var
// Seção de Declarações das variáveis 
nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva ("Digite seu nome: ")
leia(nome)
escreva("Olá, " , nome, " é um prazer te conhecer!")


Fimalgoritmo