Algoritmo "ex06_ant_suc"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2022
Var
// Seção de Declarações das variáveis 
n1, n2, n3: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva ("Digite um número: ")
leia (n1)
escreva("O antecessor de ", n1, " é ", n1-1, " e o sucessor de ", n1, " é ", n1+1)

Fimalgoritmo