Algoritmo "ex07_dobro_terco"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/08/2022
Var
// Seção de Declarações das variáveis 
n1: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número: ")
leia(n1)
limpatela
escreval ("O dobro de ",n1, " é ", n1*2)
escreva("Um terço de ",n1," é ", n1/3)

Fimalgoritmo